name: small_5x6

board: configs/boards/small_5x6_dict6x6_250_meters.npy

deep_config: configs/deep/small_5x6.yaml

deep_checkpoint:
  models/deepcharuco/small_5x6/detector.ckpt

refinenet_checkpoint:
  models/refinenet/refinenet.ckpt

deepcharuco_root:
  third_party/deepcharuco/upstream/src

nano_executable:
  third_party/aruco_nano/build/detect_batch
