# DeepChArUco config for 5x6 board (20 ChArUco IDs)

board_name: DICT_6X6_250
row_count: 6
col_count: 5
square_len: 1.0
marker_len: 0.6666666667

input_size: [320, 240]
bs_train: 8
bs_train_rn: 64
bs_val: 8
bs_val_rn: 128
num_workers: 0

train_labels: 'coco_subset/train.json'
val_labels: 'coco_subset/val.json'
train_images: 'coco_subset/train/'
val_images: 'coco_subset/val/'
